name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    defaults:

    runs-on: ubuntu-latest

    name: build

    steps:
      - name: Setup repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Run eslint and prettier
      run: yarn lint-check
